<a href="https://colab.research.google.com/github/Anubhav-1997/100-days-of-Applied-AI/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(np.arange(10))

[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


In [14]:
l=range(100) 
%timeit [i**2 for i in l]
print([i**2 for i in l])

10000 loops, best of 3: 23.2 µs per loop
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]


In [11]:
a=np.arange(100)
%timeit a**2
print(a**2)

The slowest run took 28.80 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 705 ns per loop
[   0    1    4    9   16   25   36   49   64   81  100  121  144  169
  196  225  256  289  324  361  400  441  484  529  576  625  676  729
  784  841  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681
 1764 1849 1936 2025 2116 2209 2304 2401 2500 2601 2704 2809 2916 3025
 3136 3249 3364 3481 3600 3721 3844 3969 4096 4225 4356 4489 4624 4761
 4900 5041 5184 5329 5476 5625 5776 5929 6084 6241 6400 6561 6724 6889
 7056 7225 7396 7569 7744 7921 8100 8281 8464 8649 8836 9025 9216 9409
 9604 9801]


In [15]:
b=np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
b.ndim

2

In [17]:
b.shape

(2, 3)

In [18]:
len(b)

2

In [20]:
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c.ndim

3

In [21]:
c.shape

(2, 2, 2)

In [23]:
len(c)

2

In [25]:
a=np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [27]:
a=np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.eye(3) #Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [33]:
np.diag(a)

array([1, 2, 3, 4])

In [34]:
np.random.rand(4)

array([0.35588137, 0.87795455, 0.89107299, 0.84826934])

In [35]:
np.random.randn(4)

array([ 0.11937878, -1.31529935,  0.26503859,  0.6335941 ])

In [38]:
a=np.arange(10,dtype='float64')
a[5]

5.0

In [37]:
d=np.array([1+2j,2-3j])
d.dtype

dtype('complex128')

In [42]:
a=np.diag([1,2,3])
a[1,1]

2

In [0]:
a[1,2]=5

In [44]:
a[1,2]

5

In [45]:
a

array([[1, 0, 0],
       [0, 2, 5],
       [0, 0, 3]])

In [47]:
a=np.arange(10)
a[1:8:2]

array([1, 3, 5, 7])

In [48]:
a[4:]=10
a

array([ 0,  1,  2,  3, 10, 10, 10, 10, 10, 10])

In [0]:
 a=np.arange(10)
 b=np.arange(5)
 a[5:]=b[::-1]

In [52]:
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [53]:
a=np.arange(10)
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [54]:
np.shares_memory(a,b)

True

In [55]:
b[0]=10
b

array([10,  2,  4,  6,  8])

In [56]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [57]:
c=a[::2].copy()
c

array([10,  2,  4,  6,  8])

In [58]:
np.shares_memory(a,c)

False

In [64]:
a=np.random.randint(0,20,15)
mask=(a%2==0)
b=a[mask]
print(a,'\n',b)

[ 8  2  9 12  7 10  8 10 17  8  8  6  9  9 11] 
 [ 8  2 12 10  8 10  8  8  6]


In [0]:
a[mask]=-1

In [69]:
a

array([-1, -1,  9, -1,  7, -1, -1, -1, 17, -1, -1, -1,  9,  9, 11])

In [70]:
a[[2,4,5,7,8]]

array([ 9,  7, -1, -1, 17])

In [71]:
a[[9,7]]=200
a

array([ -1,  -1,   9,  -1,   7,  -1,  -1, 200,  17, 200,  -1,  -1,   9,
         9,  11])

In [76]:
a=np.array([0,1,2,3,4])
a+1

array([1, 2, 3, 4, 5])

In [77]:
a=np.arange(5)
a+1

array([1, 2, 3, 4, 5])

In [78]:
a**2

array([ 0,  1,  4,  9, 16])

In [79]:
a=np.arange(5)
b=np.arange(5)
np.array_equal(a,b)

True

In [80]:
a.dot(b)

30

In [81]:
c=np.diag([1,2,3])
c*c

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

In [82]:
c.dot(c)

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

In [83]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [84]:
np.log(a)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [85]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [86]:
 np.sum(a)

10

In [87]:
x=np.array([[1,2],[3,3]])
x.sum(axis=0)

array([4, 5])

In [88]:
x

array([[1, 2],
       [3, 3]])

In [89]:
x.sum(axis=1)

array([3, 6])

In [90]:
x=np.array([1,2,3,4])
x.min()

1

In [91]:
x.max()

4

In [92]:
x.argmax()

3

In [93]:
x.argmin()

0

In [96]:
a=np.array([[1,2,3],[4,5,6]])
a.ravel() #flatterns

array([1, 2, 3, 4, 5, 6])

In [97]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [102]:
 a.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
a=np.arange(4*3*2).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [107]:
a[0,2,1]

5

In [0]:
b=np.sort(a,axis=1)

In [109]:
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [0]:
c=np.argsort(a,axis=1)

In [111]:
c

array([[[0, 0],
        [1, 1],
        [2, 2]],

       [[0, 0],
        [1, 1],
        [2, 2]],

       [[0, 0],
        [1, 1],
        [2, 2]],

       [[0, 0],
        [1, 1],
        [2, 2]]])